spring:
  redis:
    host: 127.0.0.1
    password: '{cipher}4b54dea2025c9ea0df1166136e9e7395f94619ca0e239c1d682639fb36cfe9a9'
    database: 1
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  rabbitmq:
    host: localhost
    port: 5672
    username: '{cipher}2400616a8d65b62db3f53aa6c8443d3a09bd895ad66b143f34c0740999c496a4'
    password: '{cipher}2400616a8d65b62db3f53aa6c8443d3a09bd895ad66b143f34c0740999c496a4'    




eureka:
    client:
      serviceUrl:
        defaultZone: http://172.16.16.250:8761/eureka/,http://172.16.16.250:8762/eureka/
    instance:
      prefer-ip-address: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 10000


ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  eureka:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG    